### ISSUE TITLE
Web instance named 'modules.bot' uses an invalid format. Names must begin with a character and may only contain alphanumeric characters, _, or -.

### ISSUE THREAD

**Issue by Mrgaton** [gomashio1596/Fortnite-LobbyBot-v2#63]
V1.5.2
Python 3.10.5
fortnitepy 3.6.4
discord.py 1.7.3
Sanic 22.6.0
Traceback (most recent call last):
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\index.py", line 94, in <module>
    bot = modules.Bot(mode,loop=loop,dev='-dev' in sys.argv,use_device_code='-use-device-code' in sys.argv,use_device_auth='-use-device-auth' in sys.argv)
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\modules\bot.py", line 146, in __init__
    self.web = Web(self, __name__)
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\modules\web.py", line 1286, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Mrgato\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\app.py", line 175, in __init__
    super().__init__(name=name)
  File "C:\Users\Mrgato\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\base\root.py", line 37, in __init__
    raise SanicException(
sanic.exceptions.SanicException: Web instance named 'modules.bot' uses an invalid format. Names must begin with a character and may only contain alphanumeric characters, _, or -.

**Comment by Mrgaton** [comment]
Ok issue fixed installing sanic 21.3.0
