### ISSUE TITLE
builtin_function_or_method' object has no attribute 'create_task

### ISSUE THREAD

**Issue by Mrgaton** [gomashio1596/Fortnite-LobbyBot-v2#64]
V1.5.2
Python 3.10.5
fortnitepy 3.6.4
discord.py 1.7.3
Sanic 21.3.0
['clients'][0]['fortnite']['email'] '' はチェック 'lambda x: x and self.email_pattern.match(x) is not None' に一致しません
['clients'][0]['fortnite']['email'] '' don't match to check 'lambda x: x and self.email_pattern.match(x) is not None'

以下のキーに問題がありました
['clients'][0]['fortnite']['email']
There was an error on these keys
['clients'][0]['fortnite']['email']

Traceback (most recent call last):
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\index.py", line 95, in <module>
    bot.setup()
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\modules\bot.py", line 1589, in setup
    self.webhook.start()
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\modules\webhook.py", line 29, in start
    self.loop_task = self.loop.create_task(self.send_loop())
AttributeError: 'builtin_function_or_method' object has no attribute 'create_task'

**Comment by Mrgaton** [comment]
ok im stupid

**Comment by Mrgaton** [comment]
V1.5.2
Python 3.10.5
fortnitepy 3.6.4
discord.py 1.7.3
Sanic 21.3.0
Traceback (most recent call last):
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\index.py", line 95, in <module>
    bot.setup()
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\modules\bot.py", line 1589, in setup
    self.webhook.start()
  File "C:\Users\Mrgato\Downloads\Fortnite-LobbyBot-v2-main\Fortnite-LobbyBot-v2-main\modules\webhook.py", line 29, in start
    self.loop_task = self.loop.create_task(self.send_loop())
AttributeError: 'builtin_function_or_method' object has no attribute 'create_task'

Ok im not

**Comment by BayGamerYT** [comment]
As far as i know fortnitepy has not been updated for python 3.10 (and not sure if with the other modules as well), can you try using an older python version? like 3.9/3.8
